enum TokenType {
    TOK_IDENT,
    TOK_INT_LIT,
    TOK_FLOAT_LIT,
    TOK_STR_LIT,
    TOK_RUNE_LIT,

    TOK_NULL,
    TOK_TRUE,
    TOK_FALSE,

    TOK_IF, TOK_ELSE, TOK_WHILE, TOK_FOR, TOK_IN,
    TOK_SWITCH, TOK_DEFAULT, TOK_BREAK, TOK_CONTINUE,

    TOK_FN, TOK_RETURN, TOK_DEFER, TOK_EXIT,

    TOK_STRUCT, TOK_ENUM,

    TOK_TRY, TOK_CATCH,

    TOK_PROCTIME,
    TOK_IMPORT,
    TOK_INTEROP,

    TOK_AS,

    TOK_TYPE_RUNE, TOK_TYPE_STR, TOK_TYPE_BOOL,
    TOK_TYPE_I8, TOK_TYPE_I16, TOK_TYPE_I32, TOK_TYPE_I64,
    TOK_TYPE_U8, TOK_TYPE_U16, TOK_TYPE_U32, TOK_TYPE_U64,
    TOK_TYPE_F16, TOK_TYPE_F32, TOK_TYPE_F64, TOK_TYPE_EXT,

    TOK_IMMUT, TOK_MUT, TOK_ASSIGN,

    TOK_EQ, TOK_NEQ,
    TOK_GT, TOK_GTE, TOK_LT, TOK_LTE,
    TOK_AND, TOK_OR, TOK_NOT,

    TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT,

    TOK_PLUSEQ, TOK_MINUSEQ, TOK_STAREQ, TOK_SLASHEQ,

    TOK_PLUSPLUS, TOK_MINUSMINUS,

    TOK_QUESTION, TOK_SLICE, TOK_COLON,
    TOK_PIPE, TOK_DOT, TOK_COMMA, TOK_ARROW,
    TOK_SEMICOLON,

    TOK_LPAREN, TOK_RPAREN,
    TOK_LBRACE, TOK_RBRACE,
    TOK_LBRACKET, TOK_RBRACKET,

    TOK_EOF,
    TOK_ERROR
};

struct Token {
    TokenType type;
    const char *start;
    int len;
    int line, col;
    bool preceded_nl;
    union {
        long   int_val;
        double float_val;
    };
};